### PR TITLE
Update MQTT-Topics.md

### PR DESCRIPTION
**Pull request by salami738**
Hello, I have seen that in the MQTT documentation some values are not sufficiently broken down and would like to suggest this documentation extension.

### CODE REVIEW

**Review by stumbaumr — COMMENTED** [review]
```
main/Internal_Heater_State | Internal backup heater state (0=inactive, 1=active)
main/External_Heater_State | External backup/booster heater state (0=inactive, 1=active)
```

I would rather change that to on/off.

**Comment by geduxas** [comment]
> ```
> main/Internal_Heater_State | Internal backup heater state (0=inactive, 1=active)
> main/External_Heater_State | External backup/booster heater state (0=inactive, 1=active)
> ```
> 
> I would rather change that to on/off.

State is indicating that heater is allowed to use for pump logic.. so it should be enabled/disabled instead of on/off.. so active/inactive i think have more meaning..

**Comment by geduxas** [comment]
Even it could be allowed/blocked state..

**Comment by salami738** [comment]
Should i modify my PR or is it ok now?

**Comment by stumbaumr** [comment]
@geduxas I believe you mix up TOP58/59 with TOP 60/61.

TOP60/61 is really if the heating element is hot/on or off...
grafik

**Comment by geduxas** [comment]
> @geduxas I believe you mix up TOP58/59 with TOP 60/61.
> 
> TOP60/61 is really if the heating element is hot/on or off... grafik

Truly don't tested, just thought documentation is right.. Heater have 2 options, enable for heating, and enable for DHW reheat. I want ability to control heater for DHW only. 

As for topic60/61 it's selectable while DHW is not integrated, from there you should select if where is electric heater is installed. From yours graph heater is used in defrost mode.. logically it's s used for room heating.

**Pull request closed without merging**
