### PR TITLE
fix v3.7

### PR DESCRIPTION
**Pull request by IgorYbema**
@Egyras please remove previous v3.7 release and make this one the v3.7 release. There was a small bug :(

### CODE REVIEW

**Comment by mi-hol** [comment]
suggest to use a new version number "3.7.1" to avoid trouble with installations while the bug was downloadable

**Comment by IgorYbema** [comment]
I understand but I want to keep it like this. The ones who will be affected and have the old v3.7 will just be a few ones.

**Comment by IgorYbema** [comment]
@egyras please remove the old v3.7 release tag and the v3.7.1 tag. This fix must replace the v3.7

**Comment by IgorYbema** [comment]
@Egyras Thank you :-)
Now please just add the release notes to the release and we are ready.

- disable wifi hotspot in settings
- move from double reset as factory reset method to 10 sec boot button press and hold
- adding a few heatpump types in type discovery
- fix rules variables print to console
- changed heatpump data in rules is now updated directly (bug)
- NTP resync works also if during reboot there was no internet/wifi
- website table refreshing is now using the JSON output and not a hard coded html output anymore
- small urldecode issue causing a crash (bug)
- JSON output is chopped into more chunks each webserver loop making it less memory hungry
- optional PCB emulation topics are now (finally) visible on the webgui

**Pull request merged**
