### PR TITLE
Add WH-ADC1216H6E5 model

### PR DESCRIPTION
**Pull request by kamaradclimber**

### CODE REVIEW

**Comment by IgorYbema** [comment]
I'll add this PR to this: https://github.com/IgorYbema/HeishaMon/pull/94

@Egyras please don't merge

**Comment by kamaradclimber** [comment]
Hello @IgorYbema ,
I am not sure to understand the workflow you propose. Is your fork the place to make PR in the future? Could you clarify?

**Comment by IgorYbema** [comment]
Yes correct. I am maintaining the code.  Still need to move to https://github.com/heishamon/HeishaMon as the main location :-)

**Comment by IgorYbema** [comment]
This PR can now be closed at is it merged into the mentioned PR in my repo now

**Comment by kamaradclimber** [comment]
Ok. It's sad though to loose issues/PR history.

**Pull request closed without merging**
