### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by mi-hol**
With recent changes 2 dependencies became unused.
I went ahead and removed them but **have no possibility to test the created bin yet!**
Build action https://github.com/mi-hol/HeishaMon/actions/runs/10759232099 is successful

### CODE REVIEW

**Comment by mi-hol** [comment]
@IgorYbema looking at .github/workflows/main.yml
the command line is now:
` run:  arduino-cli lib install ringbuffer pubsubclient arduinojson dallastemperature onewire "Adafruit NeoPixel"`

Therefore the open question is:
Is [platformio.ini](https://github.com/Egyras/HeishaMon/blob/master/platformio.ini) actually used?

**Comment by IgorYbema** [comment]
No and I don't know how that got into the repo

**Comment by geduxas** [comment]
> @IgorYbema looking at .github/workflows/main.yml the command line is now: ` run: arduino-cli lib install ringbuffer pubsubclient arduinojson dallastemperature onewire "Adafruit NeoPixel"`
> 
> Therefore the open question is: Is [platformio.ini](https://github.com/Egyras/HeishaMon/blob/master/platformio.ini) actually used?

No platformIO is not used. #376  is all it's history.

**Comment by mi-hol** [comment]
thanks for clarification, I've amended PR accordingly

**Pull request merged**
