### PR TITLE
Feature/hotspotmode

### PR DESCRIPTION
**Pull request by rpannekoek**
* Introduced `hotspot_mode` setting which specifies what should happen if WiFi connection is lost
  * Wait for connection to come back
  * Open a secured hotspot
  * Open an unsecured hotspot
* Factored out settings <-> JSON conversion code into `SettingsStruct`
* Introduced constants for settings names (instead of having string literals all over the place)
* Refactored (settings) HTML form generation. Using helper methods to render HTML form controls.
* Support debug output on Serial (facilitate debugging on e.g. a Wemos board)

### CODE REVIEW

**Comment by CurlyMoo** [comment]
It is very difficult to review this PR since it doesn't just implement the discussed changes, but also various (on first sight) unrelated changes in the codebase. Like the settings refactoring.

If those changes are mandatory, it's best practice to make it into a separate PR.

**Comment by IgorYbema** [comment]
Yes indeed. Why did you change so much for only the discussed change? This makes it very hard to merge with current other forks and branches.

**Comment by IgorYbema** [comment]
@Egyras i'll take this into my repo for testing

**Comment by rpannekoek** [comment]
I'm sorry; in my job I'm used to refactor code on-the-go, but I realize these are rather significant code changes making it harder to review.
On the other hand, the code base will deteriorate if the only goal is to keep code changes to a minimum.
Please note that https://github.com/Egyras/HeishaMon/pull/245 builds on top of these code changes (and takes some of the refactorings even further).  That means that this PR can be skipped if #245 is tested and merged.

**Comment by IgorYbema** [comment]
The biggest problem is that on my repo the alpha versions are much further than the production release here in this repo. That is why we need smaller changes here.

**Comment by CurlyMoo** [comment]
> I'm sorry; in my job I'm used to refactor code on-the-go, but I realize these are rather significant code changes making it harder to review.

There is nothing wrong with refactoring. However, 
1. I do believe that even on your job, you don't just refactor based on your own insights, but discuss the proposed changes in your development team.
2. At least in git worksflows, it's best practice to properly scope a PR. Making the review progress easier and allowing others to cherry-pick various features for backporting purposes. 

>  On the other hand, the code base will deteriorate if the only goal is to keep code changes to a minimum.

I don't see why this would be the case.

@IgorYbema These changes will increase the distance between the Igor repository and the Egyras one, more and more. Is that what we want?

**Comment by IgorYbema** [comment]
No that is not what I want so that is why I asked @egyras to ignore this for now :) 
I'll take it into my repo main and publish new to egyras to match theses PR's

**Comment by Egyras** [comment]
closing, as previuos one also closed with comments.

**Pull request closed without merging**
