### PR TITLE
ReadMe for HA integration

### PR DESCRIPTION
**Pull request by MiG-41**

### CODE REVIEW

**Comment by geduxas** [comment]
Hi, i have question regards HA integration, about automations. I have set heishamon reporting via mqtt eatch second. And i think because of that i have infinite loop's in automations. If i change for example shift value from 0 to +1 with slider so it will jump from 0->1->0 infinite.. also same behavior with other settings :) so i think it's best option is to remove automations?

**Comment by MiG-41** [comment]
I observed only ,when it is changed from 0 to 1 , and again to 0 within 1s , then i got a loop. If i only change once , then it was ok.
Check that , if you are not tring to send two values one very fast after another , ( in that case feadback from HP is not comming so fast - it arrive in max 5s).

**Comment by geduxas** [comment]
It will effect any value changed. Shift, tank temp, heating mode. I have set to mqtt send data every 1s, i think that it recives data before sending it and so will stuck in loop.

**Comment by MiG-41** [comment]
Where did you set this 1s ? In HA or HeishaMon ? ( In HeishaMon without modyfy soft it is not possible to set less then 5s).

**Comment by geduxas** [comment]
Interesting. I definitely have done MQTT retransmitting to 1s :) it's seams it is in my imagination, so don't understand why it is flipping.. maybe HA last updates done something strange?  i have flipping in all changeable options, If i change slide position for shift from 0 to +1 it will start flipping, if I change more (while flipping) to +2 it will flip in all set sequences 0, +1, +2, 0, +1, yesterday tried to switch heating mode from DHW+ROOM to ROOM, so it looped between DHW+ROMM and ROOM.  don't change anything in YAML, no more automations in my HA.

**Comment by MiG-41** [comment]
If you change in HeishaMon less then 5s , after save it will set 5 anyway... Magic trick from @IgorYbema  ;)
To change it you have to compile your own with removing this rule.

Together with a @TBomek managed to avoid this flipping ,by moving automation: part ( lines from 24 to 220 from heishamon.yaml) to file automations.yaml  , adding som id, and a  delay 5s. ( now it is sending last version of chose ,before sends imidietly what you choose , and when you made a corection before HA gets a feadback from HeishaMon , it gives such loop). But not sure , if helps you in your case , since sending first value gives a loop ( that not happen in our case).

**Comment by gregor-samosir** [comment]
It's a difference in HeishaMon between send and receive. For receive values from Heisha the limit is 5s. But yo can send commands at every time and your set command goes to an buffer in HeishaMon. This buffer is an FILO buffer, this means first in last out. If you send the temp shift to fast it maybe come to this flipping back to an value send before the last on. For details please ask Igor.

**Comment by MiG-41** [comment]
True , feadback from HeisHamon ( and HP it self) ,is something different , but i assumed , that there where no other command pending , and bufor was empty  , so command should be confirmed in HA in max 6s... )

**Comment by gregor-samosir** [comment]
It can be take longer then this 6s. If you send an set command, it will send immediately to the Heisha. But some times you don't get the answer on the first read on serial, but on the second one after 10 seconds. It depends on the Heisha how long it takes.

**Comment by MiG-41** [comment]
@geduxas ,it will be good to log this paticular command in MQTT ,  maybe from that you will notice , why HA is sending two commands ( if really) ,and what is the root of that.

**Comment by geduxas** [comment]
I loaded all weapons to monitor behavior, can't reproduce :D all week I was in pain and afraid to adjust.. yesterday I had issue :)

**Comment by MiG-41** [comment]
Important is ,to send only one clear particular command , and wait for feedback from HP , to be send again to HA (or any other Homa auttomation).

If in beetwen there will be another same type command (even with the same value) , then neverending loop is ready :)  

EDIT: Or perhaps the same value will stop somwhere ( hope in HeishaMon : ) )

**Comment by geduxas** [comment]
Just had loop. now I have logged mqtt, so it sends command, also receives status from heishamon. 
loop


image

**Comment by geduxas** [comment]
it seams that HA gets value before i trigger it., so it will set value to Heishamon, and triggers get value from heishamon.. so it will switch infinite in getting/setting

**Comment by MiG-41** [comment]
But looks like before you set to 1 you already had a loop ? 
Red arrow "Set to 1" , and before changing states...

**Comment by geduxas** [comment]
no this log is from moment i have changed value from 0 to 1 (and while in loop) changed to 2.

**Comment by MiG-41** [comment]
So you set to 1 , and then a command with set to 0 imidietly apear.
Maybe from other automation ?

**Comment by geduxas** [comment]
yes, from single device ;)  i changed that from mobile phone Homeassistant app, maybe problem with app.. i ll try from pc web browser.

**Comment by geduxas** [comment]
from PC, 1 time from 5 ended in loop.

**Comment by MiG-41** [comment]
Yo can try it with:
Put this: https://pastecode.io/s/96F1nsvMj4 to /config/automations.yaml 
In the same time remove corresponding elements from /config/configuration.yaml (like i mentioned orginally inheishamon.yaml are lines 24- 220)

Make sure ,that you have in /config/configuration.yaml line:  
`
automation: !include automations.yaml
`

, Restart HA and look , if this delays gives something.

**Comment by MiG-41** [comment]
@geduxas does it help ? Have you found other solutions ?

**Comment by geduxas** [comment]
Hi, it solves loop, but now if change value, ha will switch back after couple of seconds, but it seams after couple of other seconds it will show correctly.

**Comment by supersjimmie** [comment]
> Hi, it solves loop, but now if change value, ha will switch back after couple of seconds, but it seams after couple of other seconds it will show correctly.

Code that I see is:
```
- id: 948aadd968084dbaa1aafd0c6555d27c
  alias: Set heatshift
  trigger:
  - platform: state
    entity_id: input_number.heishamon_heatshift
  action:
  - delay: '5'
  - service: mqtt.publish
    data_template:
      topic: panasonic_heat_pump/commands/SetZ1HeatRequestTemperature
      retain: false
      payload_template: '{{ "%.0f" % (states(''input_number.heishamon_heatshift'')
        | int) }}'
  mode: single
```
I would think that the delay should follow **after** the mqtt publish.

```
  action:
  - service: mqtt.publish
    data_template:
      topic: panasonic_heat_pump/commands/SetZ1HeatRequestTemperature
      retain: false
      payload_template: '{{ "%.0f" % (states(''input_number.heishamon_heatshift'')
        | int) }}'
  - delay: '5'
  mode: single
```

**Comment by MiG-41** [comment]
Intention was , that first you have to decide with value you want to really sent , and problem was when you made a mistake , and then you want to quickly made a correction , you send two values one after another ,and you got loop.  In delay before , you can easly make that correction within 5s , and HA will send last value. 
In your suggestion will send firs value ,with can be wrong , and then it waits 5 s to send another.  
@supersjimmie I belive delay before is better.

**Comment by MiG-41** [comment]
> I definitely have done MQTT retransmitting to 1s :)

@geduxas , where did you set it ? If there is such option , maybe it reads from MQTT actual status ( with is not actual , but still previous during "change operation") ?

**Comment by geduxas** [comment]
> > I definitely have done MQTT retransmitting to 1s :)
> 
> @geduxas , where did you set it ? If there is such option , maybe it reads from MQTT actual status ( with is not actual , but still previous during "change operation") ?

In heishamon settings there is option to get values, and retransmit, i think in 0.9 it was possible to set 1s for retransmition or i thought that was possible. Now it definitely set in 5s

**Comment by MiG-41** [comment]
Ok , right , we talk about it... 
Thought that there is some options in HA . I have no idea ,why in your case value back to previous . At my case i'm seting it to what i need ,and it stays there ( but to mqtt it sents it after 5s , then it take another time  - 5s or more , to get feetback from HeatPump).

**Comment by geduxas** [comment]
Strange things, monitoring MQTT shows that data from mqtt is posted more frequent than in 5s. i have noticed that LWT value often going Offline/Online device is not disconnecting from network.

image

**Comment by MiG-41** [comment]
Can you make a full log of topic /log ? 
Maybe you have two heishamon in network ? Or the same host name ,with is fighing in mqtt broker ?

**Comment by geduxas** [comment]
No I have one device, with static IP, so no issues there. I think I found problem, so there will be something wrong with S0 meter. First I thought about that. I have disables S0 setting in heishamon, no changes, reboot, still no changes, physically disconnect S0 contacts, no changes, reboot again bam, now LWT online, and MQTT refreshes in 5s! earlier it was refreshing in random. So i think it something with S0 meter..

**Comment by IgorYbema** [comment]
Can you tell me how long the cable from panasonic to heishamon is? It seems from other users that S0 takes just too much power in some cases causing heishamon to reset or loose wifi connections when receiving s0 pulses.

**Comment by geduxas** [comment]
> Can you tell me how long the cable from panasonic to heishamon is? It seems from other users that S0 takes just too much power in some cases causing heishamon to reset or loose wifi connections when receiving s0 pulses.

2m with ferrite. Heishamon uptime don't reset, also ping respond's without timeout.

**Comment by IgorYbema** [comment]
Can you dump the 'panasonic_heat_pump/log' mqtt topic and enable mqtt logging in heishamon? 
On a Raspberry Pi mosquitto broker:  mosquitto_sub  -t panasonic_heat_pump/log/# -v

**Comment by Egyras** [comment]
Or you can install in any windows mqttLens and do checking as well

**Comment by geduxas** [comment]
> Can you dump the 'panasonic_heat_pump/log' mqtt topic and enable mqtt logging in heishamon?
> On a Raspberry Pi mosquitto broker: mosquitto_sub -t panasonic_heat_pump/log/# -v

Do I need to enable S0? because now I have disconnected everything from S0 and disabled it, so it works fine now :) I think all problems with loop it was because heieshamon went in online/offline cycles so it refreshed values in random times.. now I get update each 5s.

**Comment by IgorYbema** [comment]
Yes with S0 then please to recreate the issue :) 
Or if you ok with it you can close the issue ofcourse also :-)

**Comment by geduxas** [comment]
> Yes with S0 then please to recreate the issue :)
> Or if you ok with it you can close the issue ofcourse also :-)

it's even not an issue :D I have made offtopic in merge request, i thought MIG is one who using HA in most, so i tried to ask question about my problem :) sorry for that. ok i will enable S0, maybe I should open new  issue for that case? because we have found something. Also about logging.. it seams a little bit painfully to get logs via MQTT, is it possible to make /log page in web interface? for feature?

**Comment by IgorYbema** [comment]
I'll think about that. Should be some circulal logging as memory is limited. 
Best way is to connect a USB-TTL  to the GND and GPIO2 pins which will show complete log without network needed.

**Comment by geduxas** [comment]
I have connected S0 contacts, works ok, rebooted, still everything ok, enabled s0 meter still no problems :D strange things.. so i will wait for problems appears again and open separate case for that. By the way, I have meter with 400imp/kwh, and truly don't like readings :) 

here is example, readings values from pump an SO meter, also i have SEHLLY 3EM on main input so it newer shows spikes like heishamon S0 readings. 

image

**Comment by IgorYbema** [comment]
which one is the shelly?

**Comment by geduxas** [comment]
> which one is the shelly?

Not in graph, I have compered earlier Panasonic power consumptions and shelly readings, so as whey was almost identical, so I have moved shelly to main power input in my house, I am comparing Readings from Panasonic, and SO meter.. i think Panasonic power meter is accurate enough.

**Comment by geduxas** [comment]
here i have graphs from Shelly 3M (main house meter) and results from Heishamon

image


so S0 is just don't fit in graphs, or maybe I need to make some calculations from that ? :) 

also in meter I have Modbus interface, so I could read total kWh from meter, and if I make calculation's from kwh to kw it will match Panasonic values almost identically.

**Comment by IgorYbema** [comment]
So the S0 is way too low (only the spikes hit the correct value as it seems)?
Did you configure S0 correctly (imp/kwh)?

**Comment by geduxas** [comment]
> So the S0 is way too low (only the spikes hit the correct value as it seems)?
> Did you configure S0 correctly (imp/kwh)?

Yes set to 400imp/kwh

**Comment by IgorYbema** [comment]
Ok. 400imp/kwh is very low to have accurate s0 measuring. But heishamon tries to do it's best. What did you configure for "S0 port 1 reporting interval during standby/low power usage"?

**Comment by geduxas** [comment]
I understand that it low:) Everything left default.  60sec, 150W

**Comment by IgorYbema** [comment]
Ok. I never tested with a 400 imp/kwh meter (3 phase). I'll buy such a kwh meter and try myself. I'll come back to that. Probably the code is not good enough which these low imp/kwh.

**Comment by MiG-41** [comment]
@IgorYbema maybe simple method , with will omit second impulse :)

**Comment by IgorYbema** [comment]
@geduxas can you please post a photo how your wired the s0? I was doing some code review and can not find a reason why this is so bad. On a 400imp/kwh with about 5000 Watt load it should pulse each 1.8 sec and that is fast enough to be roughly accurate.

**Comment by geduxas** [comment]
Nothing special there about.. 4wire phone cable from heishamon to power meter, using only 2 wires, black to gnd, rend to s0_1 pin, and same red and black wire to meter pulse contacts. Where is not much to do wrong i think :)

**Comment by geduxas** [comment]
Also wiring goes near powere lines which go direct to heatpump, i have around 2-3 meters distance from meter to heatpump

**Comment by IgorYbema** [comment]
Ok hard to figure out what is going wrong here but I just ordered a 400imp/kwh myself to test this. Will report back in a few days hopefully.

**Comment by IgorYbema** [comment]
@geduxas just got my 400imp/kwh 3-phase kwh installed on my heatpump and it works fine
The calculated s0 watt is within expected watts and no spikes (running for half hour now).
Can you post a photo of your kwh meter and the connections on the heishamon to it?

**Comment by geduxas** [comment]
Maybe it's my meter doing something wrong ? :)


image

image

image

**Comment by IgorYbema** [comment]
Connections are ok. Are the led pulses constant and does the time between pulses match the watt? 

edit: time between pulses should be 3600 / 400 / kWatt or simplified 9 / kWatt (so if you are doing 5000 watt the pulses interval should be around 1.8 s).

**Comment by geduxas** [comment]
Contacts are ok, on meter side i have checked voltage 3.3v, and drops on led pulse. So i think works ok. LED now led is blinking one in 8.7sec heishamon shows  5watt?!? Something really strange here :)

**Comment by IgorYbema** [comment]
8.7 sec should be around 1000watt, does that sound ok according to the other meters you have?

So it seems that heishamon is not seeing the pulses (it does this on the rising edge, so when the voltage first goes to 0 and then goes back to 3.3v again). Is your meter fast enough to see it drop to 0?

**Comment by geduxas** [comment]
Yes HP runing on 1kw now.I have noticed drop to 1.7V maybe it's not so fast ;)

**Comment by IgorYbema** [comment]
For test, can you short the heishamon s0_1 and gnd port? To see if heishamon can see that as a pulse.

**Comment by geduxas** [comment]
Rebooted heishamon, now jt shows 35w

**Comment by IgorYbema** [comment]
And I mean not alway short but short them in pulses by hand.

**Comment by geduxas** [comment]
Tester show's min/max values so 1.43/3.77

**Comment by geduxas** [comment]
By shorting around once in 4 sec i got 31690

**Comment by IgorYbema** [comment]
Shorting manually gives some extra pulses so value is not accurate but that is ok for the test. Now we are sure heishamon can detect it. But somehow your kwh meter does not drop to 0 fully and has some internal resistance. Let me think.

**Comment by IgorYbema** [comment]
Can you please measure the resistance over the s0 port during a pulse? Is that possible? (and without heishamon connected)

**Comment by geduxas** [comment]
1.40M

**Comment by IgorYbema** [comment]
whut? during a pulse that should be almost 0 ohms.

**Comment by geduxas** [comment]
:) i think it's not shorting it.. tried to make beep from tester on short, but it doesn't.. i thik cheap China meter something doing unusual :D

**Comment by IgorYbema** [comment]
My 400imp/kwh is also china made but working fine :)

**Comment by IgorYbema** [comment]
Maybe adding some high value resistor (50-100kohm) parallel to the s0 should help dropping the voltage far enough. Try with different values from 10kohm to 200kohm. Connect it directly on s0_1 and gnd where the wires also go into.

**Comment by geduxas** [comment]
Ok, I'll try to find and test ;) thinking about same.. first thought that calculations are wrong, didn't thought to test befire asking ;)

**Comment by MiG-41** [comment]
Maybe shortcuting S0 in counted is made on some transistor Open Colector way , and polarity is important... Did you tried to switch wires from one end ?

**Comment by geduxas** [comment]
Playing with toy ;)

IMG_20210124_161749

**Comment by IgorYbema** [comment]
That is cool! Did you modify the restiance because I now see the 0v drop in the pulse.

**Comment by IgorYbema** [comment]
> Ok, I'll try to find and test ;) thinking about same.. first thought that calculations are wrong, didn't thought to test befire asking ;)

I always needed an excuse to buy myself a kwh meter for the heatpump. Now I had :)

**Comment by geduxas** [comment]
Now it's still without resitor.. so i think my tester is too slow for mesurement.. by searching in my stuff i have remembered about oscilloscope i have :D maybe pulse is too fast?

**Comment by IgorYbema** [comment]
No it seems to be around 70ms and that is normal.  I am puzzled now.

**Comment by IgorYbema** [comment]
Maybe, just what @MiG-41 said, the polarity is wrong. I see the markings + and - but maybe they just put that wrong on the labels.

**Comment by IgorYbema** [comment]
And do you have a small push button? Making sure the heishamon input is correct (we did the short test before but now want to test with push button).

**Comment by geduxas** [comment]
Now i am in shock.. because i was in hurry i left everyting as is after checking with scope.. now i have returned, and everything works fine .. what just happened :D @IgorYbema  do you have backdoor to device? :D 

..just kidding ;)

**Comment by IgorYbema** [comment]
Bad connection maybe?

**Comment by geduxas** [comment]
Where? I have mesured voltage in meter side, after that i have mesured and tested in heishamon side :D board visually seams verry good quality..  :) mystical things happening :)

**Comment by geduxas** [comment]
Everything almost matches ;)

Screenshot_20210124-193723__01

**Comment by IgorYbema** [comment]
Maybe soldering of the connector on the heishamon pcb? It's a manual job from me and maybe I made a mistake.
But then again.. if it works.. don't touch it anymore :-)

**Comment by geduxas** [comment]
Yes yes its safely laying on ground :D maybe no one will step on it :D ok, so we know that with coding is everyting ok, so if i find problem I'll write to you ;)

**Comment by IgorYbema** [comment]
Great

**Comment by geduxas** [comment]
it started to work after shorting test.. so i think it's on meter side. 

image

**Comment by IgorYbema** [comment]
Interesting find. However can not find any reason why...

**Comment by supersjimmie** [comment]
@MiG-41  you helped me a lot, some time ago, when I had some "flapping" effects in Home Assistant.
Now I still notice the flapping at the Main Power and a few others, and I just can't figure out how to fix it.
(sorry, I am not so good with this)
For the Main Power, I now see this:
```
sensor:
  #TOP0 - Power state
  - platform: mqtt
    name: Aquarea Power State
    state_topic: "panasonic_heat_pump/main/Heatpump_State"
    value_template: >-
      {%- if value == "0" -%}
        Off
      {%- elif value == "1" -%}
        On
      {%- endif -%}
```
And:
```
switch:
#Turn on/off heatpump
  - platform: mqtt
    name: Aquarea Main Power
    command_topic: "panasonic_heat_pump/commands/SetHeatpump"
    state_topic: "panasonic_heat_pump/main/Heatpump_State"
    qos: 0
    payload_on: "1"
    payload_off: "0"
    retain: false
```
I remember one of those (or both?) has to be replaced by some automation that includes a delay of 5s, but how... ?

**Comment by geduxas** [comment]
I have flapping issues too.. don't know really why it's happening.... Where's something wrong with automations. I think it's better to use heating/thermostat entity's for that.. i have tested and it's seam working much better.. just didn't find time to finish it and share.

**Comment by supersjimmie** [comment]
@geduxas  @MiG-41  it looks like it "works better" when the "new values are collected" in heishamon settings is 5 seconds.
I tried 10s and 15s, but now with 5s, it sometimes flips one time and that takes the correct value.

**Pull request merged**
